[package]
name = "mill-io"
authors = ["Citadel-tech", "Mohamed Emad <hulxxv@gmail.com>"]
description = "A generic event loop implementation built on mio."
version = "0.0.1-alpha"
edition = "2024"
repository = "https://github.com/citadel-tech/Event-Loop"
license-file = "LICENSE"
keywords = ["io", "event-loop", "mio", "async", "networking", "reactor"]

[dependencies]
lockfree = "0.5.1"
mio = { version = "1.0.3", features = ["os-poll", "net"] }

[features]
default = []
unstable-mpmc = []
unstable = ["unstable-mpmc"]

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = "0.10"
