name: Lint with Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        rust: [stable, nightly]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy
    
    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: clippy-${{ runner.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          clippy-${{ runner.os }}-${{ matrix.rust }}-
    
    - name: Run clippy (all targets)
      run: |
        if [ "${{ matrix.rust }}" = "nightly" ]; then
          cargo clippy --all-targets --features unstable -- -D warnings
        else
          cargo clippy --all-targets --no-default-features -- -D warnings
        fi
    
    - name: Run clippy (tests)
      run: |
        if [ "${{ matrix.rust }}" = "nightly" ]; then
          cargo clippy --tests --features unstable -- -D warnings
        else
          cargo clippy --tests --no-default-features -- -D warnings
        fi